runtime: python
entrypoint: gunicorn -b :$PORT main:app
env: flex

runtime_config:
    python_version: 3

handlers:
- url: /static
  static_dir: build/static/
- url: /(.*)
  script: auto

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 4